package views;

import dao.PontuacaoDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Pontuacao;

public class TelaHome extends javax.swing.JFrame {

    TelaInicial pai;
    Usuario loggedUser;
    public Fase fase;
    public int mode;
    
    public TelaHome(TelaInicial ti, JFrame midFrame, Usuario u) {
        this.pai = ti;
        if(u != null){
            loggedUser = new Usuario(u);
            midFrame.dispose();
            initComponents();
            setLocationRelativeTo(null);
            lblSaudacao.setText("Bem-vindo ao espaço, cadete "+loggedUser.getNome()+"!");
            
            ArrayList<Pontuacao> pRankGeral = new PontuacaoDAO().carregarRankingGeral();
            ArrayList<Pontuacao> pRankPessoal = new PontuacaoDAO().carregarRankingPessoal(loggedUser);
            RankingGeralTableModel rGTM = new RankingGeralTableModel(pRankGeral);
            RankingPessoalTableModel rPTM = new RankingPessoalTableModel(pRankPessoal);
            tblRankingGeral.setModel(rGTM);
            tblRankingPessoal.setModel(rPTM);
            
        }else{
            initComponents();
            setLocationRelativeTo(null);
            loggedUser = new Usuario();
            loggedUser.setLogado(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpModo = new javax.swing.ButtonGroup();
        tbpPanelHome = new javax.swing.JTabbedPane();
        pnlGuiaHome = new javax.swing.JPanel();
        btnJogar = new javax.swing.JButton();
        lblSaudacao = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblFundoFoda = new javax.swing.JLabel();
        rbtnFacil = new javax.swing.JRadioButton();
        rbtnDificil = new javax.swing.JRadioButton();
        btnCreditos = new javax.swing.JButton();
        pnlGuiaOpcoes = new javax.swing.JPanel();
        lblConfigTeclas = new javax.swing.JLabel();
        pnlGuiaJogo = new javax.swing.JPanel();
        pnlGuiaRanking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRankingGeral = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRankingPessoal = new javax.swing.JTable();
        lblRankingGeral = new javax.swing.JLabel();
        lblRankingPessoal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbpPanelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpPanelHomeMouseClicked(evt);
            }
        });

        btnJogar.setText("Jogar");
        btnJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJogarMouseClicked(evt);
            }
        });
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        lblSaudacao.setText("Bem-vindo ao espaço, cadete!");

        btnLogout.setText("Deslogar");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        lblFundoFoda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/naveFodaFundo_2.jpg"))); // NOI18N

        btnGrpModo.add(rbtnFacil);
        rbtnFacil.setText("Fácil");

        btnGrpModo.add(rbtnDificil);
        rbtnDificil.setText("Difícil");

        btnCreditos.setText("Créditos");
        btnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGuiaHomeLayout = new javax.swing.GroupLayout(pnlGuiaHome);
        pnlGuiaHome.setLayout(pnlGuiaHomeLayout);
        pnlGuiaHomeLayout.setHorizontalGroup(
            pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGuiaHomeLayout.createSequentialGroup()
                        .addComponent(btnJogar)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnFacil)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDificil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblFundoFoda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlGuiaHomeLayout.setVerticalGroup(
            pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addGroup(pnlGuiaHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJogar)
                    .addComponent(rbtnFacil)
                    .addComponent(rbtnDificil)
                    .addComponent(btnCreditos))
                .addGap(18, 18, 18)
                .addComponent(lblFundoFoda, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpPanelHome.addTab("Home", pnlGuiaHome);

        lblConfigTeclas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConfigTeclas.setText("Configuração de teclas");

        javax.swing.GroupLayout pnlGuiaOpcoesLayout = new javax.swing.GroupLayout(pnlGuiaOpcoes);
        pnlGuiaOpcoes.setLayout(pnlGuiaOpcoesLayout);
        pnlGuiaOpcoesLayout.setHorizontalGroup(
            pnlGuiaOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfigTeclas)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        pnlGuiaOpcoesLayout.setVerticalGroup(
            pnlGuiaOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfigTeclas)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        tbpPanelHome.addTab("Opções", pnlGuiaOpcoes);

        pnlGuiaJogo.setPreferredSize(new java.awt.Dimension(500, 420));

        javax.swing.GroupLayout pnlGuiaJogoLayout = new javax.swing.GroupLayout(pnlGuiaJogo);
        pnlGuiaJogo.setLayout(pnlGuiaJogoLayout);
        pnlGuiaJogoLayout.setHorizontalGroup(
            pnlGuiaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        pnlGuiaJogoLayout.setVerticalGroup(
            pnlGuiaJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tbpPanelHome.addTab("Fase", pnlGuiaJogo);

        tblRankingGeral.setAutoCreateRowSorter(true);
        tblRankingGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Posição", "Email", "Pontos", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRankingGeral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(tblRankingGeral);
        if (tblRankingGeral.getColumnModel().getColumnCount() > 0) {
            tblRankingGeral.getColumnModel().getColumn(0).setHeaderValue("Posição");
            tblRankingGeral.getColumnModel().getColumn(1).setHeaderValue("Email");
            tblRankingGeral.getColumnModel().getColumn(2).setHeaderValue("Pontos");
            tblRankingGeral.getColumnModel().getColumn(3).setHeaderValue("Data");
        }

        tblRankingPessoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Posição", "Pontos", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRankingPessoal);

        lblRankingGeral.setText("Ranking Geral");

        lblRankingPessoal.setText("Ranking Pessoal");

        javax.swing.GroupLayout pnlGuiaRankingLayout = new javax.swing.GroupLayout(pnlGuiaRanking);
        pnlGuiaRanking.setLayout(pnlGuiaRankingLayout);
        pnlGuiaRankingLayout.setHorizontalGroup(
            pnlGuiaRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGuiaRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(pnlGuiaRankingLayout.createSequentialGroup()
                        .addGroup(pnlGuiaRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRankingGeral)
                            .addComponent(lblRankingPessoal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlGuiaRankingLayout.setVerticalGroup(
            pnlGuiaRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuiaRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRankingGeral)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblRankingPessoal)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tbpPanelHome.addTab("Ranking", pnlGuiaRanking);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPanelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPanelHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed

    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJogarMouseClicked
        if(fase == null){
            if(rbtnDificil.isSelected()) tbpPanelHome.addTab("Space Invaders", (fase = new Fase(loggedUser, 2, this)));
            else tbpPanelHome.addTab("Space Invaders", (fase = new Fase(loggedUser, 1, this)));
        }else{
            if(rbtnFacil.isSelected()) fase.setMode(1);
            else if(rbtnDificil.isSelected()) fase.setMode(2);
            fase.inicializarFlags();
            fase.pause(false);
        }
        tbpPanelHome.setSelectedIndex(tbpPanelHome.getTabCount()-1);
        for(int i = 0; i < 4; i++) tbpPanelHome.setEnabledAt(i, false);
    }//GEN-LAST:event_btnJogarMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        this.pai.setEnabled(true);
        this.pai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void tbpPanelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpPanelHomeMouseClicked
        ArrayList<Pontuacao> pRankGeral = new PontuacaoDAO().carregarRankingGeral();
        ArrayList<Pontuacao> pRankPessoal = new PontuacaoDAO().carregarRankingPessoal(loggedUser);
        RankingGeralTableModel rGTM = new RankingGeralTableModel(pRankGeral);
        RankingPessoalTableModel rPTM = new RankingPessoalTableModel(pRankPessoal);
        tblRankingGeral.setModel(rGTM);
        tblRankingPessoal.setModel(rPTM);
    }//GEN-LAST:event_tbpPanelHomeMouseClicked

    private void btnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditosMouseClicked
        JOptionPane.showMessageDialog(this, "Créditos aos desenvolvedores: \nBruno C.A.F., \nLucas Moraes Soares de Souza, \n Matheus Borges Teixeira, \n ao mito, Professor Matheus Dimas,\n e a Yann Braga pelo tutorial.");
    }//GEN-LAST:event_btnCreditosMouseClicked

    public void salvarPontuacao(Usuario u){
        PontuacaoDAO pDao = new PontuacaoDAO();
        pDao.registrarScore(u);
    }
    
    public void sairJogo(){
        if(loggedUser.isLogado()){
            for(int i = 0; i < 4; i++) tbpPanelHome.setEnabledAt(i, true);
            tbpPanelHome.setSelectedIndex(0);
        }else{
            this.pai.setEnabled(true);
            this.pai.setVisible(true);
            this.dispose();
        }
    }
    
    public void setMode(int mode){
        this.mode = mode;
    }
    
    public void unloggedStart(){
        tbpPanelHome.addTab("Space Invaders", (fase = new Fase(loggedUser, mode, this)));
        tbpPanelHome.setSelectedIndex(tbpPanelHome.getTabCount()-1);
        for(int i = 0; i < 4; i++) tbpPanelHome.setEnabledAt(i, false);
        fase.grabFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.ButtonGroup btnGrpModo;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConfigTeclas;
    private javax.swing.JLabel lblFundoFoda;
    private javax.swing.JLabel lblRankingGeral;
    private javax.swing.JLabel lblRankingPessoal;
    private javax.swing.JLabel lblSaudacao;
    private javax.swing.JPanel pnlGuiaHome;
    private javax.swing.JPanel pnlGuiaJogo;
    private javax.swing.JPanel pnlGuiaOpcoes;
    private javax.swing.JPanel pnlGuiaRanking;
    private javax.swing.JRadioButton rbtnDificil;
    private javax.swing.JRadioButton rbtnFacil;
    private javax.swing.JTable tblRankingGeral;
    private javax.swing.JTable tblRankingPessoal;
    private javax.swing.JTabbedPane tbpPanelHome;
    // End of variables declaration//GEN-END:variables
}